apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
        - name: rubyapp
          image: oluwasanmivic123/docker_web:latest
          env:
            - name: DATABASE_URL
              value: "postgres://victoria:victoria@postgres:5432/your-postgres-database"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: rubyapp
spec:
  selector:
    app: rubyapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
