# Git Repository Resource for Open Flights
#Apply the configuration with edited environment variables using the command: kubectl apply -f pipelineresources.yaml."

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: open-flights
spec:
  type: git
  params:
    - name: revision
      value: main  # or master depending on your branch
    - name: url
      value: https://github.com/Victoria-OA/test.git

--- 
# Docker Image Resource for Web
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: web-docker-image
spec:
  type: image
  params:
  - name: url
    value: oluwasanmivic123/docker_web:latest

--- 
# Docker Image Resource for Database
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: db-docker-image
spec:
  type: image
  params:
  - name: url
    value: oluwasanmivic123/docker_db:latest
