# Kubernetes Secret for Docker Authentication

# use the command (echo -n "username/password" | base64) to get the secrets, apply with Kubectl apply -f secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: kubernetes.io/basic-auth
stringData:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
