#create env variables for the containerization on the terminal with the command below


##############################################################
### kubectl create secret generic postgres-credentials \ #######
###  --from-literal=POSTGRES_USER=your_username \        #######
###  --from-literal=POSTGRES_PASSWORD=your_password \    #######
###  --from-literal=POSTGRES_DB=your_database            #######
##############################################################


# Dockerfile for PostgreSQL 15

# ---------------------------

# Use an official PostgreSQL base image with version 15
FROM postgres:15

# Set build arguments for PostgreSQL credentials
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB

# Expose the default PostgreSQL port
EXPOSE 5432

