version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://victoria:victoria@db:5432/budget_app_development
   # command: ["sh", "-c", "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"]

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: victoria
      POSTGRES_PASSWORD: victoria
      POSTGRES_DB: open_flights_development
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
