#open-flights app
# define the Ruby base image 
FROM ruby:2.6-buster

# Set the working directory inside the container to /app
WORKDIR /app

# Install dependencies
   # Install PostgreSQL client
RUN apt-get update -qq && apt-get install -y postgresql-client

   #Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

    # Install Yarn
RUN npm install -g yarn

    # Install Bundler version 2.3.6
RUN gem install bundler -v 2.3.6

# Copy the Gemfile and Gemfile.lock to /app
COPY ./open-flights/Gemfile /app
COPY ./open-flights/Gemfile.lock /app

# Configure the local nokogiri version to avoid conflicts
RUN bundle config --local nokogiri '1.13.2'

# Install Ruby dependencies using Bundler based on Gemfile and Gemfile.lock
RUN bundle install

# Copy the entire application directory into /app
COPY ./open-flights /app

# Precompile assets
RUN bundle exec rails assets:precompile

# Expose port 3000, which is typically used for Rails applications
EXPOSE 3000

# Define the command to run the Rails server
#CMD ["rails", "server", "-b", "0.0.0.0"]
CMD ["sh", "-c", "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"]