# ArgoCD Secret for GitHub Credentials
# use the command (echo -n "username/password" | base64) to get the secrets, apply with Kubectl apply -f argocd-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
