# ArgoCD RBAC Configurations
# ConfigMap for RBAC Policy
#Apply the configuration using the command: kubectl apply -f argocd-rbac-cm.yaml."

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, "Victoria-OA", role:admin
