apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: https://github.com/Victoria-OA/test.git
      usernameKey: username
      passwordKey: password
