# Secret for PostgreSQL
# use the command (echo -n "username/password" | base64) to get the secrets, apply with Kubectl apply -f secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: <base64-encoded-username>
  postgres-password: <base64-encoded-password>
