# Service for Ruby App
#Apply the configuration using the command: kubectl apply -f service.yaml."
apiVersion: v1
kind: Service
metadata:
  name: rubyapp
spec:
  selector:
    app: rubyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
