# Deployment for Ruby App
#Apply the configuration with edited environment variables using the command: kubectl apply -f web.yaml."

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubyapp
  template:
    metadata:
      labels:
        app: rubyapp
    spec:
      containers:
        - name: rubyapp
          image: oluwasanmivic123/docker_web:latest
          env:
            - name: DATABASE_URL
              value: "postgres://$(postgres_user):$(postgres_password)@postgres:5432/your-postgres-database"
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: postgres-secret

---
# Service for Ruby App
apiVersion: v1
kind: Service
metadata:
  name: rubyapp
spec:
  selector:
    app: rubyapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
